services:
  helpdesk:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/HelpDesk

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2910
      POSTGRES_DB: HelpDesk
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: